// Code generated by protoc-gen-go. DO NOT EDIT.
// source: OCoPiAgent.proto

/*
Package opencopilot is a generated protocol buffer package.

It is generated from these files:
	OCoPiAgent.proto

It has these top-level messages:
	StatusRequest
	StartServiceRequest
	ConfigureServiceRequest
	StopServiceRequest
	SetServiceGRPCRequest
	GetServiceLogsRequest
	ServiceLogLine
	Status
*/
package opencopilot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StartServiceRequest struct {
	ImageRef string `protobuf:"bytes,1,opt,name=image_ref,json=imageRef" json:"image_ref,omitempty"`
}

func (m *StartServiceRequest) Reset()                    { *m = StartServiceRequest{} }
func (m *StartServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*StartServiceRequest) ProtoMessage()               {}
func (*StartServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StartServiceRequest) GetImageRef() string {
	if m != nil {
		return m.ImageRef
	}
	return ""
}

type ConfigureServiceRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *ConfigureServiceRequest) Reset()                    { *m = ConfigureServiceRequest{} }
func (m *ConfigureServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigureServiceRequest) ProtoMessage()               {}
func (*ConfigureServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ConfigureServiceRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type StopServiceRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *StopServiceRequest) Reset()                    { *m = StopServiceRequest{} }
func (m *StopServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*StopServiceRequest) ProtoMessage()               {}
func (*StopServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StopServiceRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type SetServiceGRPCRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	Port        int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *SetServiceGRPCRequest) Reset()                    { *m = SetServiceGRPCRequest{} }
func (m *SetServiceGRPCRequest) String() string            { return proto.CompactTextString(m) }
func (*SetServiceGRPCRequest) ProtoMessage()               {}
func (*SetServiceGRPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetServiceGRPCRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *SetServiceGRPCRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GetServiceLogsRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *GetServiceLogsRequest) Reset()                    { *m = GetServiceLogsRequest{} }
func (m *GetServiceLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetServiceLogsRequest) ProtoMessage()               {}
func (*GetServiceLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetServiceLogsRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type ServiceLogLine struct {
	Line string `protobuf:"bytes,1,opt,name=line" json:"line,omitempty"`
}

func (m *ServiceLogLine) Reset()                    { *m = ServiceLogLine{} }
func (m *ServiceLogLine) String() string            { return proto.CompactTextString(m) }
func (*ServiceLogLine) ProtoMessage()               {}
func (*ServiceLogLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceLogLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type Status struct {
	AgentId  string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Services []*Status_AgentService `protobuf:"bytes,2,rep,name=services" json:"services,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Status) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *Status) GetServices() []*Status_AgentService {
	if m != nil {
		return m.Services
	}
	return nil
}

type Status_AgentService struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
}

func (m *Status_AgentService) Reset()                    { *m = Status_AgentService{} }
func (m *Status_AgentService) String() string            { return proto.CompactTextString(m) }
func (*Status_AgentService) ProtoMessage()               {}
func (*Status_AgentService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *Status_AgentService) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Status_AgentService) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "opencopilot.StatusRequest")
	proto.RegisterType((*StartServiceRequest)(nil), "opencopilot.StartServiceRequest")
	proto.RegisterType((*ConfigureServiceRequest)(nil), "opencopilot.ConfigureServiceRequest")
	proto.RegisterType((*StopServiceRequest)(nil), "opencopilot.StopServiceRequest")
	proto.RegisterType((*SetServiceGRPCRequest)(nil), "opencopilot.SetServiceGRPCRequest")
	proto.RegisterType((*GetServiceLogsRequest)(nil), "opencopilot.GetServiceLogsRequest")
	proto.RegisterType((*ServiceLogLine)(nil), "opencopilot.ServiceLogLine")
	proto.RegisterType((*Status)(nil), "opencopilot.Status")
	proto.RegisterType((*Status_AgentService)(nil), "opencopilot.Status.AgentService")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OCoPiAgent service

type OCoPiAgentClient interface {
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*Status, error)
	// rpc StartService(StartServiceRequest) returns (Status) {}
	// rpc ConfigureService(ConfigureServiceRequest) returns (Status) {}
	// rpc StopService(StopServiceRequest) returns (Status) {}
	GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (OCoPiAgent_GetServiceLogsClient, error)
	SetServiceGRPC(ctx context.Context, in *SetServiceGRPCRequest, opts ...grpc.CallOption) (*Status, error)
}

type oCoPiAgentClient struct {
	cc *grpc.ClientConn
}

func NewOCoPiAgentClient(cc *grpc.ClientConn) OCoPiAgentClient {
	return &oCoPiAgentClient{cc}
}

func (c *oCoPiAgentClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/opencopilot.OCoPiAgent/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oCoPiAgentClient) GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (OCoPiAgent_GetServiceLogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_OCoPiAgent_serviceDesc.Streams[0], c.cc, "/opencopilot.OCoPiAgent/GetServiceLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &oCoPiAgentGetServiceLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OCoPiAgent_GetServiceLogsClient interface {
	Recv() (*ServiceLogLine, error)
	grpc.ClientStream
}

type oCoPiAgentGetServiceLogsClient struct {
	grpc.ClientStream
}

func (x *oCoPiAgentGetServiceLogsClient) Recv() (*ServiceLogLine, error) {
	m := new(ServiceLogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *oCoPiAgentClient) SetServiceGRPC(ctx context.Context, in *SetServiceGRPCRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/opencopilot.OCoPiAgent/SetServiceGRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OCoPiAgent service

type OCoPiAgentServer interface {
	GetStatus(context.Context, *StatusRequest) (*Status, error)
	// rpc StartService(StartServiceRequest) returns (Status) {}
	// rpc ConfigureService(ConfigureServiceRequest) returns (Status) {}
	// rpc StopService(StopServiceRequest) returns (Status) {}
	GetServiceLogs(*GetServiceLogsRequest, OCoPiAgent_GetServiceLogsServer) error
	SetServiceGRPC(context.Context, *SetServiceGRPCRequest) (*Status, error)
}

func RegisterOCoPiAgentServer(s *grpc.Server, srv OCoPiAgentServer) {
	s.RegisterService(&_OCoPiAgent_serviceDesc, srv)
}

func _OCoPiAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCoPiAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opencopilot.OCoPiAgent/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCoPiAgentServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OCoPiAgent_GetServiceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetServiceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OCoPiAgentServer).GetServiceLogs(m, &oCoPiAgentGetServiceLogsServer{stream})
}

type OCoPiAgent_GetServiceLogsServer interface {
	Send(*ServiceLogLine) error
	grpc.ServerStream
}

type oCoPiAgentGetServiceLogsServer struct {
	grpc.ServerStream
}

func (x *oCoPiAgentGetServiceLogsServer) Send(m *ServiceLogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _OCoPiAgent_SetServiceGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceGRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OCoPiAgentServer).SetServiceGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opencopilot.OCoPiAgent/SetServiceGRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OCoPiAgentServer).SetServiceGRPC(ctx, req.(*SetServiceGRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OCoPiAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opencopilot.OCoPiAgent",
	HandlerType: (*OCoPiAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _OCoPiAgent_GetStatus_Handler,
		},
		{
			MethodName: "SetServiceGRPC",
			Handler:    _OCoPiAgent_SetServiceGRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetServiceLogs",
			Handler:       _OCoPiAgent_GetServiceLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "OCoPiAgent.proto",
}

func init() { proto.RegisterFile("OCoPiAgent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x4e, 0xfa, 0x30,
	0x14, 0xc6, 0xd9, 0xfe, 0x7f, 0x90, 0x1d, 0x10, 0x4d, 0x91, 0x88, 0xe3, 0x66, 0x36, 0x5e, 0x70,
	0xb5, 0x18, 0x34, 0x31, 0x31, 0xc4, 0xc4, 0x70, 0x41, 0x88, 0x44, 0xc9, 0x16, 0xaf, 0xc9, 0x64,
	0x87, 0xa5, 0x09, 0xae, 0xb3, 0x2b, 0xbe, 0x8a, 0xaf, 0xe9, 0x23, 0x98, 0x75, 0x63, 0x30, 0x32,
	0x13, 0xb9, 0x6b, 0x4f, 0xfb, 0x7d, 0xe7, 0xec, 0xf7, 0x75, 0x70, 0xfa, 0x32, 0xe2, 0x33, 0xf6,
	0x18, 0x60, 0x28, 0xed, 0x48, 0x70, 0xc9, 0x49, 0x83, 0x47, 0x18, 0x2e, 0x78, 0xc4, 0x56, 0x5c,
	0xd2, 0x13, 0x38, 0x76, 0xa5, 0x27, 0xd7, 0xb1, 0x83, 0x1f, 0x6b, 0x8c, 0x25, 0x1d, 0x40, 0xdb,
	0x95, 0x9e, 0x90, 0x2e, 0x8a, 0x4f, 0xb6, 0xc0, 0xac, 0x4c, 0x7a, 0x60, 0xb0, 0x77, 0x2f, 0xc0,
	0xb9, 0xc0, 0x65, 0x57, 0xb3, 0xb4, 0xbe, 0xe1, 0xd4, 0x55, 0xc1, 0xc1, 0x25, 0x1d, 0xc2, 0xf9,
	0x88, 0x87, 0x4b, 0x16, 0xac, 0x05, 0xee, 0xe9, 0x2e, 0xa1, 0xb9, 0xe0, 0xa1, 0xf4, 0x58, 0x88,
	0x62, 0xce, 0xfc, 0x4c, 0xda, 0xc8, 0x6b, 0x13, 0x9f, 0xde, 0x01, 0x71, 0x25, 0x8f, 0x0e, 0x17,
	0x3e, 0x43, 0xc7, 0xc5, 0xcd, 0xa0, 0x63, 0x67, 0x36, 0xfa, 0xbb, 0x96, 0x10, 0xf8, 0x1f, 0x71,
	0x21, 0xbb, 0xba, 0xa5, 0xf5, 0xab, 0x8e, 0x5a, 0xd3, 0x7b, 0xe8, 0x8c, 0x73, 0xbf, 0x29, 0x0f,
	0xe2, 0x03, 0x66, 0xb9, 0x82, 0xd6, 0x56, 0x38, 0x65, 0x21, 0x26, 0x1d, 0x56, 0x2c, 0xc4, 0xec,
	0xb2, 0x5a, 0xd3, 0x2f, 0x0d, 0x6a, 0x29, 0x6e, 0x72, 0x01, 0x75, 0x2f, 0x09, 0x65, 0xeb, 0x77,
	0xa4, 0xf6, 0x13, 0x9f, 0x0c, 0xa1, 0x1e, 0xa7, 0x5e, 0x71, 0x57, 0xb7, 0xfe, 0xf5, 0x1b, 0x03,
	0xcb, 0xde, 0xc9, 0xcc, 0x4e, 0x1d, 0x6c, 0x95, 0xe9, 0x86, 0x5a, 0xae, 0x30, 0x6f, 0xa1, 0xb9,
	0x7b, 0x42, 0x5a, 0xa0, 0xe7, 0x2d, 0x74, 0xe6, 0x93, 0x33, 0xa8, 0xaa, 0xe0, 0xd4, 0xa7, 0x1b,
	0x4e, 0xba, 0x19, 0x7c, 0x6b, 0x00, 0xdb, 0x97, 0x42, 0x1e, 0xc0, 0x48, 0x50, 0xa4, 0xa3, 0x9a,
	0x25, 0xdd, 0x33, 0x34, 0x66, 0xbb, 0xe4, 0x8c, 0x56, 0xc8, 0x2b, 0xb4, 0x8a, 0x28, 0x09, 0x2d,
	0x5c, 0x2c, 0xe5, 0x6c, 0xf6, 0x8a, 0x66, 0x05, 0x9e, 0xb4, 0x72, 0xad, 0x91, 0xa7, 0x84, 0xf2,
	0x6e, 0xe2, 0x7b, 0xb6, 0xa5, 0xcf, 0xe1, 0x97, 0x19, 0xdf, 0x6a, 0xea, 0x77, 0xb8, 0xf9, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x4d, 0xf3, 0xda, 0x9b, 0x22, 0x03, 0x00, 0x00,
}
