// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PlumbAgent.proto

/*
Package plumb is a generated protocol buffer package.

It is generated from these files:
	PlumbAgent.proto

It has these top-level messages:
	StatusRequest
	StartServiceRequest
	ConfigureServiceRequest
	StopServiceRequest
	SetServiceGRPCRequest
	GetServiceLogsRequest
	ServiceLogLine
	Status
*/
package plumb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StartServiceRequest struct {
	ImageRef string `protobuf:"bytes,1,opt,name=image_ref,json=imageRef" json:"image_ref,omitempty"`
}

func (m *StartServiceRequest) Reset()                    { *m = StartServiceRequest{} }
func (m *StartServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*StartServiceRequest) ProtoMessage()               {}
func (*StartServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StartServiceRequest) GetImageRef() string {
	if m != nil {
		return m.ImageRef
	}
	return ""
}

type ConfigureServiceRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *ConfigureServiceRequest) Reset()                    { *m = ConfigureServiceRequest{} }
func (m *ConfigureServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigureServiceRequest) ProtoMessage()               {}
func (*ConfigureServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ConfigureServiceRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type StopServiceRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *StopServiceRequest) Reset()                    { *m = StopServiceRequest{} }
func (m *StopServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*StopServiceRequest) ProtoMessage()               {}
func (*StopServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StopServiceRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type SetServiceGRPCRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	Port        int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *SetServiceGRPCRequest) Reset()                    { *m = SetServiceGRPCRequest{} }
func (m *SetServiceGRPCRequest) String() string            { return proto.CompactTextString(m) }
func (*SetServiceGRPCRequest) ProtoMessage()               {}
func (*SetServiceGRPCRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetServiceGRPCRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *SetServiceGRPCRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GetServiceLogsRequest struct {
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *GetServiceLogsRequest) Reset()                    { *m = GetServiceLogsRequest{} }
func (m *GetServiceLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetServiceLogsRequest) ProtoMessage()               {}
func (*GetServiceLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetServiceLogsRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type ServiceLogLine struct {
	Line string `protobuf:"bytes,1,opt,name=line" json:"line,omitempty"`
}

func (m *ServiceLogLine) Reset()                    { *m = ServiceLogLine{} }
func (m *ServiceLogLine) String() string            { return proto.CompactTextString(m) }
func (*ServiceLogLine) ProtoMessage()               {}
func (*ServiceLogLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceLogLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

type Status struct {
	AgentId  string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Services []*Status_AgentService `protobuf:"bytes,2,rep,name=services" json:"services,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Status) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *Status) GetServices() []*Status_AgentService {
	if m != nil {
		return m.Services
	}
	return nil
}

type Status_AgentService struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
}

func (m *Status_AgentService) Reset()                    { *m = Status_AgentService{} }
func (m *Status_AgentService) String() string            { return proto.CompactTextString(m) }
func (*Status_AgentService) ProtoMessage()               {}
func (*Status_AgentService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *Status_AgentService) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Status_AgentService) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "plumb.StatusRequest")
	proto.RegisterType((*StartServiceRequest)(nil), "plumb.StartServiceRequest")
	proto.RegisterType((*ConfigureServiceRequest)(nil), "plumb.ConfigureServiceRequest")
	proto.RegisterType((*StopServiceRequest)(nil), "plumb.StopServiceRequest")
	proto.RegisterType((*SetServiceGRPCRequest)(nil), "plumb.SetServiceGRPCRequest")
	proto.RegisterType((*GetServiceLogsRequest)(nil), "plumb.GetServiceLogsRequest")
	proto.RegisterType((*ServiceLogLine)(nil), "plumb.ServiceLogLine")
	proto.RegisterType((*Status)(nil), "plumb.Status")
	proto.RegisterType((*Status_AgentService)(nil), "plumb.Status.AgentService")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PlumbAgent service

type PlumbAgentClient interface {
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*Status, error)
	StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*Status, error)
	ConfigureService(ctx context.Context, in *ConfigureServiceRequest, opts ...grpc.CallOption) (*Status, error)
	StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*Status, error)
	GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (PlumbAgent_GetServiceLogsClient, error)
	SetServiceGRPC(ctx context.Context, in *SetServiceGRPCRequest, opts ...grpc.CallOption) (*Status, error)
}

type plumbAgentClient struct {
	cc *grpc.ClientConn
}

func NewPlumbAgentClient(cc *grpc.ClientConn) PlumbAgentClient {
	return &plumbAgentClient{cc}
}

func (c *plumbAgentClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/plumb.PlumbAgent/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumbAgentClient) StartService(ctx context.Context, in *StartServiceRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/plumb.PlumbAgent/StartService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumbAgentClient) ConfigureService(ctx context.Context, in *ConfigureServiceRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/plumb.PlumbAgent/ConfigureService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumbAgentClient) StopService(ctx context.Context, in *StopServiceRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/plumb.PlumbAgent/StopService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumbAgentClient) GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (PlumbAgent_GetServiceLogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlumbAgent_serviceDesc.Streams[0], c.cc, "/plumb.PlumbAgent/GetServiceLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &plumbAgentGetServiceLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlumbAgent_GetServiceLogsClient interface {
	Recv() (*ServiceLogLine, error)
	grpc.ClientStream
}

type plumbAgentGetServiceLogsClient struct {
	grpc.ClientStream
}

func (x *plumbAgentGetServiceLogsClient) Recv() (*ServiceLogLine, error) {
	m := new(ServiceLogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *plumbAgentClient) SetServiceGRPC(ctx context.Context, in *SetServiceGRPCRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/plumb.PlumbAgent/SetServiceGRPC", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlumbAgent service

type PlumbAgentServer interface {
	GetStatus(context.Context, *StatusRequest) (*Status, error)
	StartService(context.Context, *StartServiceRequest) (*Status, error)
	ConfigureService(context.Context, *ConfigureServiceRequest) (*Status, error)
	StopService(context.Context, *StopServiceRequest) (*Status, error)
	GetServiceLogs(*GetServiceLogsRequest, PlumbAgent_GetServiceLogsServer) error
	SetServiceGRPC(context.Context, *SetServiceGRPCRequest) (*Status, error)
}

func RegisterPlumbAgentServer(s *grpc.Server, srv PlumbAgentServer) {
	s.RegisterService(&_PlumbAgent_serviceDesc, srv)
}

func _PlumbAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumbAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumb.PlumbAgent/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumbAgentServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlumbAgent_StartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumbAgentServer).StartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumb.PlumbAgent/StartService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumbAgentServer).StartService(ctx, req.(*StartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlumbAgent_ConfigureService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumbAgentServer).ConfigureService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumb.PlumbAgent/ConfigureService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumbAgentServer).ConfigureService(ctx, req.(*ConfigureServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlumbAgent_StopService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumbAgentServer).StopService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumb.PlumbAgent/StopService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumbAgentServer).StopService(ctx, req.(*StopServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlumbAgent_GetServiceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetServiceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlumbAgentServer).GetServiceLogs(m, &plumbAgentGetServiceLogsServer{stream})
}

type PlumbAgent_GetServiceLogsServer interface {
	Send(*ServiceLogLine) error
	grpc.ServerStream
}

type plumbAgentGetServiceLogsServer struct {
	grpc.ServerStream
}

func (x *plumbAgentGetServiceLogsServer) Send(m *ServiceLogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _PlumbAgent_SetServiceGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceGRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumbAgentServer).SetServiceGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plumb.PlumbAgent/SetServiceGRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumbAgentServer).SetServiceGRPC(ctx, req.(*SetServiceGRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlumbAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plumb.PlumbAgent",
	HandlerType: (*PlumbAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _PlumbAgent_GetStatus_Handler,
		},
		{
			MethodName: "StartService",
			Handler:    _PlumbAgent_StartService_Handler,
		},
		{
			MethodName: "ConfigureService",
			Handler:    _PlumbAgent_ConfigureService_Handler,
		},
		{
			MethodName: "StopService",
			Handler:    _PlumbAgent_StopService_Handler,
		},
		{
			MethodName: "SetServiceGRPC",
			Handler:    _PlumbAgent_SetServiceGRPC_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetServiceLogs",
			Handler:       _PlumbAgent_GetServiceLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "PlumbAgent.proto",
}

func init() { proto.RegisterFile("PlumbAgent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0x86, 0x4d, 0xac, 0xd6, 0x1c, 0x3f, 0x2a, 0xa7, 0x4a, 0x35, 0x2d, 0xc5, 0x0e, 0xbd, 0xf0,
	0x2a, 0x94, 0xb4, 0x74, 0xd9, 0x0f, 0x58, 0x16, 0x2f, 0x44, 0x90, 0x45, 0x92, 0x1f, 0x20, 0xd1,
	0x8c, 0x61, 0x40, 0x93, 0x6c, 0x32, 0xd9, 0xff, 0xb0, 0x97, 0xfb, 0x8f, 0x97, 0x4c, 0x62, 0xcc,
	0x87, 0x0b, 0xeb, 0x5d, 0xe6, 0xcc, 0x79, 0xdf, 0x39, 0x9e, 0xf7, 0x11, 0xfa, 0xab, 0x7d, 0x74,
	0xd8, 0x3c, 0x38, 0xd4, 0xe5, 0x9a, 0x1f, 0x78, 0xdc, 0xc3, 0x86, 0x1f, 0x57, 0xc8, 0x17, 0xe8,
	0x9a, 0xdc, 0xe2, 0x51, 0x68, 0xd0, 0xa7, 0x88, 0x86, 0x9c, 0xe8, 0xf0, 0xd5, 0xe4, 0x56, 0xc0,
	0x4d, 0x1a, 0x3c, 0xb3, 0x2d, 0x4d, 0xcb, 0xf8, 0x1d, 0x14, 0x76, 0xb0, 0x1c, 0xba, 0x0e, 0xe8,
	0x6e, 0x24, 0x4d, 0xa4, 0xa9, 0x62, 0xb4, 0x44, 0xc1, 0xa0, 0x3b, 0x72, 0x07, 0xdf, 0x66, 0x9e,
	0xbb, 0x63, 0x4e, 0x14, 0xd0, 0x92, 0xee, 0x17, 0x74, 0xb6, 0x9e, 0xcb, 0x2d, 0xe6, 0xd2, 0x60,
	0xcd, 0xec, 0x54, 0xda, 0xce, 0x6a, 0x0b, 0x9b, 0x5c, 0x01, 0x9a, 0xdc, 0xf3, 0x2f, 0x17, 0x3e,
	0xc2, 0xd0, 0xa4, 0xc7, 0x41, 0xe7, 0xc6, 0x6a, 0xf6, 0x71, 0x2d, 0x22, 0x7c, 0xf2, 0xbd, 0x80,
	0x8f, 0xe4, 0x89, 0x34, 0x6d, 0x18, 0xe2, 0x9b, 0xdc, 0xc0, 0x70, 0x9e, 0xf9, 0x2d, 0x3d, 0x27,
	0xbc, 0x60, 0x96, 0xdf, 0xd0, 0x3b, 0x09, 0x97, 0xcc, 0xa5, 0xf1, 0x0b, 0x7b, 0xe6, 0xd2, 0xb4,
	0x59, 0x7c, 0x93, 0x57, 0x09, 0x9a, 0xc9, 0xba, 0x71, 0x0c, 0x2d, 0x2b, 0x8e, 0xe3, 0xe4, 0xf7,
	0x59, 0x9c, 0x17, 0x36, 0xfe, 0x87, 0x56, 0x98, 0x78, 0x85, 0x23, 0x79, 0x52, 0x9f, 0xb6, 0x75,
	0x55, 0x13, 0x69, 0x69, 0x89, 0x56, 0x13, 0x39, 0x1e, 0xf7, 0x95, 0xf5, 0xaa, 0xff, 0xa0, 0x93,
	0xbf, 0xc1, 0x1e, 0xc8, 0x99, 0xb9, 0xcc, 0x6c, 0x1c, 0x40, 0x43, 0x44, 0x26, 0x7e, 0xb4, 0x62,
	0x24, 0x07, 0xfd, 0xa5, 0x0e, 0x70, 0xa2, 0x03, 0x75, 0x50, 0xe2, 0x25, 0x24, 0x43, 0x0e, 0x0a,
	0xef, 0xa6, 0xeb, 0x50, 0xbb, 0x85, 0x2a, 0xa9, 0xe1, 0x2d, 0x74, 0xf2, 0xcc, 0x60, 0x6e, 0xdc,
	0x32, 0x48, 0x55, 0xf1, 0x0c, 0xfa, 0x65, 0x78, 0xf0, 0x67, 0xda, 0xf4, 0x0e, 0x55, 0x55, 0x93,
	0x6b, 0x68, 0xe7, 0x18, 0xc2, 0x71, 0x76, 0x5f, 0xe6, 0xaa, 0x2a, 0x5d, 0x40, 0xaf, 0x98, 0x3a,
	0xfe, 0x48, 0x5b, 0xce, 0xc2, 0xa0, 0x0e, 0x8f, 0x06, 0x85, 0xb8, 0x49, 0xed, 0x8f, 0x84, 0xf7,
	0x31, 0x04, 0x79, 0x20, 0x33, 0xab, 0xb3, 0x9c, 0x56, 0x66, 0xd9, 0x34, 0xc5, 0x7f, 0xf3, 0xef,
	0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x7c, 0x17, 0xfc, 0xaf, 0x03, 0x00, 0x00,
}
